directives:
  # allegro hand
  - add_model:
    name: allegro_hand
    file: package://drake/models/allegro_hand_description/urdf/allegro_hand_description_left.urdf
  
  - add_weld:
    parent: world
    child: hand_root